version: '3.8'

services:
  jenkins:
    build: .
    container_name: marvin_jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - USER_CHOCOLATEEN_PASSWORD=${USER_CHOCOLATEEN_PASSWORD}
      - USER_VAUGIE_G_PASSWORD=${USER_VAUGIE_G_PASSWORD}
      - USER_I_DONT_KNOW_PASSWORD=${USER_I_DONT_KNOW_PASSWORD}
      - USER_NASSO_PASSWORD=${USER_NASSO_PASSWORD}
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_home: